### ISSUE TITLE
Dependencies: python3 ipaddress 

### ISSUE THREAD

**Issue by uwabami** [kusm/dnschecker#1]
Hi,

```
% python3 dnschecker.py
Traceback (most recent call last):
  File "dnschecker.py", line 12, in <module>
      from network import Network, NetworkRangeError
        File "/home/uwabami/Sources/dnschecker/network.py", line 13, in <module>
            import ipaddress
            ImportError: No module named ipaddress
Traceback (most recent call last):
```

But python3-ipaddress is not provided Debian 7.x

What shoud we do?

**Comment by kenkov** [comment]
Python standard module "ipaddress" is provided by only Python 3.3 or later.
Debian 7.x provides Python 3.2, therefore `ImportError` raised.

f454558 adds ipaddress.py, which implements some functions which
have the same API as Python standard module "ipaddress".

I made sure that this commit made dnschecker work well in Debian 7.x. with Python3.2
provided by a package.

**Comment by uwabami** [comment]
I don't confirm about license issue. 

BTW.,  can you fix alternate way that without python-ipaddress out source trree?

**Comment by kenkov** [comment]
c038b7d revises importing problem.

Now dnschecker uses Python standard module "ipaddress" when using Python3.3 or later, otherwise uses ipaddr.py implemented by myself.
